### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by cowwoc** [slugify/slugify#133]
Please add `module-info.java` to this project. Otherwise, Maven warns:

```
Required filename-based automodules detected: [slugify-3.0.4.jar]. Please don't publish this project to a public artifact repository!
```

and it prevents the use of `jlink`.

**Comment by dtrunk90** [comment]
Thanks for your report. Version 3.0.5 will contain that file and should be available within the next hour.

**Comment by cowwoc** [comment]
Thank you!
