### ISSUE TITLE
add chrylic support

### ISSUE THREAD

**Issue by domdorn** [slugify/slugify#15]
I have a few urls with chrylic characters and like to slugify them.
I found a javascript page that does this
http://www.lexilogos.com/keyboard/russian_conversion.htm
the mapping is defined in
http://www.lexilogos.com/clavier/conru.js

example text: "Смысловые галлюцинации" -> "Smyslovye Gallyutsinatsii"

Any hints on how I can integrate this into slugify? 
would simply adding a replacements_ru.properties do the trick? 
Or creating this map in java as customReplacements() ? 

I also found a quite exhaustive list of anyChar -> latin in string.js
https://github.com/jprichardson/string.js/blob/master/lib/string.js#L13
maybe we could integrate this into slugify? 

thanks,
Dominik

**Comment by dtrunk90** [comment]
I need your support here as I'm not familiar with chrylic characters.
I switched from language specific property files to one property file independant of the language.

You can fork the repository, add your stuff into `src/main/resources/replacements.properties`, make a test method in `core/src/test/java/com/github/slugify/SlugifyTest.java`  and make a pull request.

**Comment by dtrunk90** [comment]
See pull request #20
