### ISSUE TITLE
Greek characters are not translated without a locale in version 3.0.5

### ISSUE THREAD

**Issue by borjab** [slugify/slugify#150]
In Slugify version 2.x it was introduced the capability to Slugify greek characters. 
Now, with version 3.0.5 this (Kotlin) test will fail

```
class SlugifyTest {
    private val slugify = Slugify.builder().build()

    @Test
    fun `greek chars`() {
        val slugified = slugify.slugify("Γκόλφω, βάδιζε μπροστά ξανθή ψυχή!")

        assertThat(slugified).isEqualTo("gkolfw-badize-mprosta-ksanthh-psyxh")
    }
}
```

Is the Greek support dropped without specifying a locale?

**Comment by dtrunk90** [comment]
It looks like you didn't enabled transliteration. Check the README for how to enable it.

This test passes:
```java

  @Test
  /* default */ void givenStringWhenTransliteratorIsUsedWithoutLocaleThenSlugify() {
    final Slugify slugify = Slugify.builder()
        .transliterator(true)
        .build();

    final String expected = "nkolpho-badize-mprosta-xanthe-psyche"; // not "gkolfw-badize-mprosta-ksanthh-psyxh"
    final String actual = slugify.slugify("Γκόλφω, βάδιζε μπροστά ξανθή ψυχή!");

    assertEquals(expected, actual,
        format(ASSERT_EQUALS_MESSAGE_FORMAT, DEFAULT_LOCALE, expected, actual));
  }
```

Feel free to reopen or create another issue if the result is not the expected one.

**Comment by borjab** [comment]
Thanks a lot @dtrunk90. A fast reading of the readme and not knowing what a transliteration was made me think that this was something for Gradle. And having an IBM lib for that makes a lot of sense.

Note that this changes the end result (Probably for better. I am not Greek but I just need to maintain it). For example
> Γκόλφω, βάδιζε μπροστά ξανθή ψυχή!

Changes from
> gkolfw-badize-mprosta-ksanthh-psyxh

to:
> nkolpho-badize-mprosta-xanthe-psyche
