### ISSUE TITLE
Locale issue on lowercase conversion

### ISSUE THREAD

**Issue by utkuozdemir** [slugify/slugify#17]
In `com.github.slugify.slugify(String input)`
```java
     input = Normalizer.normalize(input, Normalizer.Form.NFD)
			.replaceAll("[^\\p{ASCII}]", "")
			.replaceAll("[^\\w+]", "-")
			.replaceAll("\\s+", "-")
			.replaceAll("[-]+", "-")
			.replaceAll("^-", "")
			.replaceAll("-$", "");

	if (getLowerCase()) {
		input = input.toLowerCase();
	}
```

Here, lowercase conversion can un-slugify the input depending on the Locale JVM is using.
For example, in Turkish locale, capitalization has exception in the letter I: I <-> ı and i <-> İ. So, if lowercase switch is used, the word `ALTINDAĞ` should be slugified to `altindag` but it slugifies to `altındag` (with Turkish ı).

Possible solutions: 
- lowercase both before and after normalization.
- lowercase using English locale (I would prefer this one).

You can also create a constructor that has signature (as in String class):
`public Slugify(final boolean lowerCase, Locale locale)`

**Comment by utkuozdemir** [comment]
Update: I did a fix and created a pull request.

**Comment by dtrunk90** [comment]
Thanks for your pull request. I'll merge and make a new release this weekend.

**Comment by dtrunk90** [comment]
Isn't it correct to slugify `ALTINDAĞ` to `altındag`. As you said: I <-> ı and i <-> İ
Or do I misunderstand something?

I'm finally not happy to hardcode a locale.

**Comment by utkuozdemir** [comment]
No, it should slugify `ALTINDAĞ` to `altindag`, not `altındag`. The problem is, the letter **ı** should never exist in a slug, it's one of the Turkish characters, not valid in URLs etc. You can try here: http://slugify.net/

Locale-specific (turkish) case conversion is breaking the correctly slugified Strings, i.e. `ALTINDAĞ` ---slug---> `ALTINDAG` ---lowercase---> `altındag`

If you lowercase **after** slugifying the string, you can never be sure that if that case conversion broke your slugification or not. So, finally we got two solutions:
1- Slugify, lowercase then slugify again to be sure. (If you lowercase before slugification, lowercase function will not change case of some letters)
2- Slugify then lowercase in English locale (because the letters in the slugified string are English characters only).

So, I think actually hardcoding a locale is not wrong, but leaving it to the system locale is. What if the locale of my island-country-with-10-population lowercases capital A to b (`ALTINDAĞ` -> `bltındbg`), would it be a correct slugification?

I picked second.

**Comment by dtrunk90** [comment]
And that's what the replacement file is for. It's for language specific special characters like umlauts in german. So try to add it here and make a new pull request: https://github.com/slugify/slugify/blob/master/core/src/main/resources/replacements.properties
