### ISSUE TITLE
How do I use this as jstl?

### ISSUE THREAD

**Issue by choudharyrahul** [slugify/slugify#19]
I downloaded and kept slugify-integration-jstl-2.1.3.jar in my lib folder and followed your example. I keep getting
 javax.el.ELException: Problems calling function 'slg:slugify'
java.lang.ClassNotFoundException: com.github.slugify.Slugify

**Comment by dtrunk90** [comment]
> If you want to use Slugify in your JSPs you need the JSTL Integration **and the library itself**.

As you don't seem to use Maven the dependency will not be automatically resolved. So you need to add it manually.

Please close if it works.

**Comment by choudharyrahul** [comment]
thanks. I was missing core jar file.
