### ISSUE TITLE
Using transliteration with lowerCase=false lowercases the string

### ISSUE THREAD

**Issue by jglaszka** [slugify/slugify#212]
## Description
When using `transliteration=true` flag, the `lowerCase=false` flag is not working properly. Its expected to preserve existing letter case, but it is changed to lowercase. For example for input `Test AAA`, output should be `Test-AAA` but is `test-aaa`.
 

## Bug Reproduction
```
 @Test
    public void shouldTransliterate() {
        // given
        Slugify s = Slugify.builder()
                .lowerCase(false)
                .transliterator(true)
                .build();


        // when
        String normalized = s.slugify("Świeże mleko");

        // now
        assertThat(normalized).isEqualTo("swieze-mleko");

        // fails: expected, because the lowerCase=false is set
        assertThat(normalized).isEqualTo("Swieze-Mleko");
    }
```

## Version
slugify = "3.0.6"
icu4j = "75.1"

**Comment by dtrunk90** [comment]
Thanks for reporting and providing a test case. This will be fixed with the next upcoming release once #213 is fixed.

**Comment by dtrunk90** [comment]
3.0.7 is released and should be available in Maven Central within the next few hours.

**Comment by jglaszka** [comment]
Thank you!
