### ISSUE TITLE
Plus sign duality

### ISSUE THREAD

**Issue by bgalek** [slugify/slugify#22]
Hello. I think, that "plus sign" should be removed from slugified string by default - it's problematic because of it's duality in URL - sometimes you mean space (%20) like in https://www.google.com/?q=test+string and sometimes you mean "+" like in 2+2 (2%2b2). I expect slug to generate string only containing [A-Z a-z 0-9 \-].

If you agree with me I could prepare a pull request, or hope for resolving this problem in next version ;)

**Comment by dtrunk90** [comment]
I do understand your argumentation but I'm not sure if it's good practice to remove the plus sign. This library replaces spaces with a minus sign. So there's no duality with the plus sign. Let me sleep on it for several nights. Hopefully some more people will join this discussion.

**Comment by bgalek** [comment]
I'll show you an example:

`
new URL("http://localhost/".concat(new Slugify().slugify("Digitalkamera Mark II + ob.")));
`

will produce: 

`http://localhost/digitalkamera-mark-ii-+-ob`

if you pass this url to chrome it will parse "+" as space 
trying to access `http://localhost/digitalkamera-mark-ii-%20-ob`

So I need to encode the whole slugified string so it becomes:
`digitalkamera-mark-ii-%2B-ob`, and then make it an url.
Then it truly points to desired address. 

So the question that I want you to answer: is slugify library made mainly for web purposes or not?
If so - we should remove “+” signs during slugification, so nobody will have to encode slug, or if the library is for more general purposes, I'll use `setCustomReplacements` function or force encoding (depending on my needs) - and we don't have anything to discuss ;)

PS. I have checked javascript equivilant libraries:
https://www.npmjs.com/package/slug - removes "+" by default
https://www.npmjs.com/package/slugify (deprecated) - leaves "+" by default
https://github.com/pid/speakingurl (seems very popular - 600+ stars) - removes "+" by default

PS2. maybe some kind of "webSafe" flag during Slugify constructor or maybe a method like toUrlSafeString()?

**Comment by dtrunk90** [comment]
That sounds reasonable. I'm currently thinking about encoding slugified urls anyway as its for web purposes. An option to set the separator (`-` by default) would be nice as well.

**Comment by bgalek** [comment]
I think slugifing strings is mainlny for avoiding encoding to make urls more readeable, so i don't have any http://localhost/nice-name-but-with-ugly-%2b%2b-chars but http://localhost/nice-name-without-ugly-chars

<personal opinion>
if it's mailny for web, just make slugified string using only [a-z0-9\-], don't bother users with encoding :)
</personal opinion>

PS. setting separator sounds cool ;)

**Comment by bgalek** [comment]
need any help?:)

**Comment by dtrunk90** [comment]
Feel free to open a pull request. I need some more free time. :-(

**Comment by bgalek** [comment]
I've made PR, I'll be happy to discuss possible merge ;) https://github.com/slugify/slugify/pull/33

**Comment by bgalek** [comment]
this pr is getting old 😢

**Comment by dtrunk90** [comment]
Sorry. I'll take a look at it this evening.
