### ISSUE TITLE
Support slugify with underscore

### ISSUE THREAD

**Issue by mateusduboli** [slugify/slugify#36]
The wikipedia article about [Semantic URL](https://en.wikipedia.org/wiki/Semantic_URL) states:

> Slugs are generally entirely lowercase, with accented characters replaced by letters from the English alphabet and whitespace characters **replaced by a dash or an underscore** to avoid being encoded.

Currently the library only uses dashes (`-`) to enconde strings,  this could be supported.

**Comment by dtrunk90** [comment]
Version 2.1.7 is released and contains a new method `withUnderscoreSeparator(boolean)`.
