### ISSUE TITLE
Using "đã" to "a" not to "da"

### ISSUE THREAD

**Issue by nqdung230690** [slugify/slugify#43]
Using "đã" to "a" not to "da"

**Comment by dtrunk90** [comment]
As I'm not a native speaker of your language I would appreciate if you could add your language specific replacements to `core/src/main/resources/replacements.properties` and do a pull request.

**Comment by nqdung230690** [comment]
My language is Vietnamese. I don't know how to pull request

**Comment by dtrunk90** [comment]
Ok. Then I'll put it into the file. Are there any other replacements I should be aware of?

**Comment by dtrunk90** [comment]
Please try the new Transliterator Feature by calling `withTransliterator(true)` and close the issue if the result is okay.
