### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by anfe0690** [slugify/slugify#45]
Hi, I found an article about romanization (https://en.wikipedia.org/wiki/Romanization), that could be useful if you are thinking in adding support for other languages, like for example Japanese (https://en.wikipedia.org/wiki/Romanization_of_Japanese).

**Comment by Enalmada** [comment]
I need to internationalize my urls and found slugify.  Unfortunately it returns empty results for many languages.  While looking around for alternatives, I noticed that this code seems to return sensible results for almost every language: https://github.com/osinka/slugify/blob/master/src/main/scala/Slugify.scala.  

I am totally guessing the reason it works for more languages is the use of a transliterator (com.ibm.icu.text.Transliterator)?   

How about slugify tries to use the transliterator as a fallback if the current path returns an empty result?  This seems like it would be pretty safe and easy while at the same time enabling nearly complete international support.

**Comment by dtrunk90** [comment]
That's a good suggestion. Unfortunately I don't have enough time to implement it yet. Feel free to fork and send a pull request.

**Comment by dtrunk90** [comment]
I've added `icu4j` to use it's `Transliterator`. You can activate it by calling `withTransliterator(true)`.

**Comment by Enalmada** [comment]
Nice!  Seems to work great.
