### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by bgalek** [slugify/slugify#51]
Hello!
I'm curious about performance of the lib, do you think that creating jmh module would be ok for you? I could setup jmh and then we could think about some tests? :) What do you think? :)

**Comment by dtrunk90** [comment]
Sure. Feel free to fork.

**Comment by dtrunk90** [comment]
I think a performance library shouldn't be part of slugify itself. You can create an encapsulated java application to test the performance. For example by using Spring AOPs Performance Monitoring or as you suggested JMH. Or maybe doing the performance tests as unit tests?

**Comment by bgalek** [comment]
I've made additional module for the benchmarks - separating it from the lib to another project will cause fast degradation and abandonment ;) this module should not be part of jar that will be published to maven of course :) I'll make PR so you could share your opinion ;)

**Comment by bgalek** [comment]
see https://github.com/slugify/slugify/pull/52 it's a start. We could think about more cases, and could think about algorithm optimization ;)
