### ISSUE TITLE
Gradle on Android gives DexArchiveBuilderException: Failed to process

### ISSUE THREAD

**Issue by SamuelMarks** [slugify/slugify#53]
Here is the line I added to my build.gradle:
```
compile 'com.github.slugify:slugify:2.2'
```

Which worked fine in IDE; but then trying to build and I got this:
```
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process .gradle/caches/modules-2/files-2.1/com.github.slugify/slugify/2.2/3a3bbcfcb4deb9a4693eed5862dc09c129d37078/slugify-2.2.jar
```

**Comment by Dragas** [comment]
Can confirm. It appears to occur on builds that target SDKs below 26. You should read https://developer.android.com/studio/write/java8-support.html though.

**Comment by SamuelMarks** [comment]
Yeah I ended up just including your old version: https://github.com/stereostream/stereostream-android/blob/master/app/src/main/java/io/complicated/stereostream/utils/Slugify.java

**Comment by dtrunk90** [comment]
Support for Java 7 has been dropped. Didn't noticed SDK < 26 (which is Android < 8) still uses Java 7?! Can someone confirm that, so I'll revert the changes as [Android 6 is still on over 30% of the devices](https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/).

**Comment by Dragas** [comment]
Yeah, all APIs below 21 are on java 7.

**Comment by dtrunk90** [comment]
@SamuelMarks can you confirm and close this issue if it works what @abhi2717 suggested?

**Comment by SamuelMarks** [comment]
Hadn't looked at the project in a while, just upgraded the Android and REST API dependencies.

Would prefer to support more devices, I have `minSdkVersion 16`. So will stick with my separate Slugify.java file that I extracted from your project.
