### ISSUE TITLE
Persian dose not work

### ISSUE THREAD

**Issue by azizkhani** [slugify/slugify#54]
Hi
slugify dose not work for Persian unicode like
تست
عزیزخانی

**Comment by khodabandelu** [comment]
it is my problem .please fix .

**Comment by dtrunk90** [comment]
Did you tried with transliterator enabled? You'll need the icu4j dependency for that. If there's still something which needs some additional fix feel free to create a `slugify_fa.properties` in a PR. I'm not a native speaker so this is better to be done by native speakers.

**Comment by dtrunk90** [comment]
No feedback yet, closed.
