### ISSUE TITLE
Allow to call methods statically

### ISSUE THREAD

**Issue by jalik** [slugify/slugify#55]
The lib is nice, however I wonder why you need to create an instance of `Slugify` and calling methods on it, instead of just calling a static method like `Slugify.slugify(String)`.
Since it's a utility class, wouldn't it be better to do this way ?

**Comment by tbrannt** [comment]
```
Slugify slg = slg.withCustomReplacement("hello", "world").withCustomReplacement("foo", "bar");
// or multiple at once
slg = slg.withCustomReplacements(new HashMap<String, String>() {{
	put("hello", "world");
	put("foo", "bar");
}});

String result = slg.slugify("hello foo");
// result: world-bar
Or if you want case sensitivity:

Slugify slg = new Slugify().withLowerCase(false);
```

These samples show that instantiation is used to hold a certain configuration

**Comment by dtrunk90** [comment]
As @tbrannt stated we need an instance in order to save some config stuff.
