### ISSUE TITLE
Caused by: java.lang.IllegalAccessException: no such method: io.appium.java_client.events.EventFiringObjectFactory.lambda$0(List,Listener)boolean/invokeStatic

### ISSUE THREAD

**Issue by abhi2717** [slugify/slugify#58]
I got a runtime error: 
1. Caused by: java.lang.IllegalAccessException: no such method: io.appium.java_client.events.EventFiringObjectFactory.lambda$0(List,Listener)boolean/invokeStatic

2. Caused by: java.lang.NoClassDefFoundError: org/springframework/context/support/AbstractApplicationContext

3. Caused by: java.lang.ClassNotFoundException: Class org.springframework.context.support.AbstractApplicationContext not found

Build.gradle:
apply plugin: 'com.android.application'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.abchauhan.customerkiosk"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

    }

    dependencies {

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        testCompile 'org.testng:testng:6.9.10'
        implementation fileTree(include: ['*.jar'], dir: 'libs')
        implementation 'com.android.support:appcompat-v7:28.0.0-rc02'
        implementation 'com.android.support.constraint:constraint-layout:1.1.3'
        implementation 'com.android.support:design:28.0.0-rc02'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
        implementation files('libs/byte-buddy-1.8.15.jar')
        implementation files('libs/client-combined-3.14.0.jar')
        implementation files('libs/client-combined-3.14.0-sources.jar')
        implementation files('libs/commons-codec-1.10.jar')
        implementation files('libs/commons-exec-1.3.jar')
        implementation files('libs/commons-logging-1.2.jar')
        implementation files('libs/guava-25.0-jre.jar')
        implementation files('libs/httpclient-4.5.5.jar')
        implementation files('libs/httpcore-4.4.9.jar')
        implementation files('libs/java-client-6.1.0.jar')
        implementation files('libs/okhttp-3.10.0.jar')
        implementation files('libs/okio-1.14.1.jar')
    }

}
dependencies {
}

Using:
Android studio- 3.1.4
Appium Jars- 6.1.0
Selenium Jars - 3.14

**Comment by dtrunk90** [comment]
Pls check if the exception is coming from slugify. Slugify doesn't have any spring related dependencies.

**Comment by abhi2717** [comment]
Should change the appium jar?

**Comment by abhi2717** [comment]
Should I change the version of appium jar?

**Comment by dtrunk90** [comment]
`Caused by: java.lang.ClassNotFoundException: Class org.springframework.context.support.AbstractApplicationContext not found`

It states it cannot find the class `org.springframework.context.support.AbstractApplicationContext` (which is part of `spring-context`) in your classpath.
