### ISSUE TITLE
Turkish character correct conversions example

### ISSUE THREAD

**Issue by egemenozkan** [slugify/slugify#60]
Hello,
There is Seo Friendly correct conversion in Turkish.  Please check and correct them.
Lowercase
ö -> o
ş  -> s
ç -> c
ı -> i
ü -> u
I - > i
İ -> i
ğ->g
Uppercase
Ö -> o
Ş  -> s
Ç  -> c
I -> i
İ->i
Ğ->g
Ü->u

**Comment by egemenozkan** [comment]
I have sent the pull request. Thank you.

**Comment by dtrunk90** [comment]
Thank you. I need to take a look why the tests are failing.

**Comment by dtrunk90** [comment]
Replacements are part of 3.0.0 now.
