### ISSUE TITLE
License metadata missing

### ISSUE THREAD

**Issue by dsvensson** [slugify/slugify#64]
The release jars files do not inform the Apache 2.0 license that at least GitHub has assigned to this project, which prevents automatic tooling for classifying this project, using for example: 

https://github.com/jk1/Gradle-License-Report

...but I guess any tool would have the same problem.

**Comment by dtrunk90** [comment]
Could you please check if the problem still exists for version 3.0.0?

**Comment by dtrunk90** [comment]
Tried it myself. `com.github.jk1.dependency-license-report` correctly reports Apache 2.0 as license now.
