### ISSUE TITLE
Reduce the dependency size

### ISSUE THREAD

**Issue by fabriceci** [slugify/slugify#68]
The “icu4j” dependency adds 12,6 mb to the project/binary, which is huge for a library/utility function. It will be great to reduce that.

**Comment by Dziman** [comment]
Quick and might be a little bit ugly solution: https://github.com/slugify/slugify/pull/77
Though you can just exclude `icu4j` in your pom:
```
<dependency>
	<groupId>com.github.slugify</groupId>
	<artifactId>slugify</artifactId>
	<exclusions>
		<exclusion>
			<groupId>com.ibm.icu</groupId>
			<artifactId>icu4j</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```
But it could lead to runtime exception if transliterator for some reason will be enabled.

**Comment by dtrunk90** [comment]
Rewrite is work in progress. See the [rewrite branch](https://github.com/slugify/slugify/tree/rewrite). icu4j will be an optional dependency by then.

**Comment by fabriceci** [comment]
@dtrunk90 Very cool, thanks for your good work!
