### ISSUE TITLE
Transcription of Cyrillic ъ, ь, Ъ and Ь

### ISSUE THREAD

**Issue by gunnarbittersmann** [slugify/slugify#72]
IMHO, the characters ъ (U+044A), ь (U+044C), Ъ (U+042A) and Ь (U+042C) shouldn’t be transcribed as `'`, but shouldn’t be transcribed at all. (At least not for Russian language. For other languages, other rules might apply, i.e. ъ in Bulgarian is a vowel: a.)
cf. https://de.wikipedia.org/wiki/Kyrillisches_Alphabet#Russisch

**Comment by dtrunk90** [comment]
I'm not that familiar with cyrillic. Could you please check if everything works as expected in 3.0.0 now?

**Comment by dtrunk90** [comment]
No feedback yet, closed.
