### ISSUE TITLE
Project maintenance state

### ISSUE THREAD

**Issue by hsebouai** [slugify/slugify#78]
Hi, we are using `slugify` in our code base and we noticed that there was not updates since April 2021. 

Is the project still alive and maintained?

If we need a transitive dependency update because of security scan, can we propose a PR?

**Comment by dtrunk90** [comment]
Hi, sorry I didn't had time to maintain this project yet. I'm planning to rewrite it.

**Comment by dtrunk90** [comment]
3.0.0 is released now. Dependencies should be up-to-date. Feel free to open up a PR if you need to bump versions.

**Comment by hsebouai** [comment]
Thank you for the updates and the rewrite, it works as a charm.
