### ISSUE TITLE
Can't build without credentials

### ISSUE THREAD

**Issue by dhoss** [slugify/slugify#92]
I don't use gradle so I'm probably missing something but I've created a fork and gradle won't get past the credential check: 

```
gradle build

> Configure project :
Reckoned version: 0.1.0-SNAPSHOT

FAILURE: Build failed with an exception.

* Where:
Build file '/home/devin/projects/slugify/build.gradle' line: 106

* What went wrong:
A problem occurred evaluating root project 'slugify'.
> Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 400ms
```

I would expect this not to be a requirement on a developer's machine unless they were publishing releases themselves but again, I'm sure I'm missing some conventional gradle wisdom.  I'm happy to fill in dummy credentials while developing but it seems unwieldy.

**Comment by dtrunk90** [comment]
Thanks for reporting. Now you should be able to build without credentials.
